### ISSUE TITLE
All pyspec tests fail with nil pointer dereference

### ISSUE THREAD

**Issue by Rjected** [ethereum/hive#1147]
We run the pyspec tests in CI and see this in the pyspec tests after the recent PR to use the correct image:

```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 94 [running]:
github.com/ethereum/hive/hivesim.runTest.func2.1()
	/go/pkg/mod/github.com/ethereum/hive@v0.0.0-20240715150147-c87a99dccfce/hivesim/testapi.go:387 +0x6c
panic({0xdf7b00?, 0x16d2860?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/ethereum/hive/simulators/ethereum/engine/types.FromBeaconExecutableData(...)
	/source/engine/types/types.go:197
main.(*EngineNewPayload).ExecutableData(0xc00013d740)
	/source/pyspec/types.go:152 +0x54
main.(*EngineNewPayload).Execute(0xc00013d740, {0x10ebbe0, 0x17bcf60}, {0x10f9878, 0xc00007c200})
	/source/pyspec/types.go:173 +0x47
main.(*EngineNewPayload).ExecuteValidate(0xc00013d740, {0x10ebbe0?, 0x17bcf60?}, {0x10f9878?, 0xc00007c200?})
	/source/pyspec/types.go:186 +0x3f
main.(*TestCase).run(0xc0000ef5c0, 0xc0002e2b40)
	/source/pyspec/runner.go:118 +0x7cc
github.com/ethereum/hive/hivesim.runTest.func2()
	/go/pkg/mod/github.com/ethereum/hive@v0.0.0-20240715150147-c87a99dccfce/hivesim/testapi.go:397 +0x8c
created by github.com/ethereum/hive/hivesim.runTest in goroutine 15
	/go/pkg/mod/github.com/ethereum/hive@v0.0.0-20240715150147-c87a99dccfce/hivesim/testapi.go:383 +0x48d
```

see simulator output here:
https://github.com/paradigmxyz/reth/actions/runs/10275727472/job/28472629363

**Comment by fjl** [comment]
I've checked this, and it appears the upstream fixtures have a totally different format now that isn't supported by the test runner.

**Comment by fjl** [comment]
They are developing a new version of the pyspec simulator over in execution-spec-tests, so maybe no point in trying to fix up the existing one...
