### ISSUE TITLE
`engine-withdrawals` suite fails with nil pointer dereference on reth

### ISSUE THREAD

**Issue by Rjected** [ethereum/hive#1185]
We are running into issues with the `engine-withdrawals` suite:
```
CLMocker: Adding engine client d65f8fd0
>> (94bc3602) {"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["latest",false]}
<< (94bc3602) {"jsonrpc":"2.0","id":1,"result":{"hash":"0xf62b6ae287c6cdc2f1bda80d0ce83cff49aa8665d0477605f9c157355885f511","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0xb13210209bd72e7902c597ee31321eddddbfc739eeffbd902092ac50a0326fe2","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":"0x0","number":"0x0","gasLimit":"0x2fefd8","gasUsed":"0x0","timestamp":"0x1234","extraData":"0x","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","baseFeePerGas":"0x3b9aca00","withdrawalsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","size":"0x221","uncles":[],"transactions":[],"withdrawals":[]}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x530e78]

goroutine 7324 [running]:
math/big.(*Int).Cmp(0xc000350080?, 0x1853808?)
	/usr/local/go/src/math/big/int.go:381 +0x18
github.com/ethereum/hive/simulators/ethereum/engine/helper.CheckTTD({0x1869200, 0xc000350080}, {0x1853798?, 0xc0005560a0?})
	/source/helper/helper.go:280 +0xd2
github.com/ethereum/hive/simulators/ethereum/engine/helper.WaitForTTD({0x1869200, 0xc000350080}, 0x44bf9d?, 0xc000756120, {0x1853798, 0xc0005560a0})
	/source/helper/helper.go:296 +0x11d
created by github.com/ethereum/hive/simulators/ethereum/engine/helper.WaitAnyClientForTTD in goroutine 50
	/source/helper/helper.go:343 +0x19f
```
See: https://github.com/paradigmxyz/reth/actions/runs/12324993003/job/34404030526

This might be because we are in the process of removing the total difficulty, so tests might need to be updated

**Comment by fjl** [comment]
I'm on it. It's the same issue with Geth, since we have also removed totalDifficulty.
