### ISSUE TITLE
docker build failed when run hive

### ISSUE THREAD

**Issue by sunqiLoveSnow** [ethereum/hive#254]
-> environment
 # docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

 # go version
go version go1.12 linux/amd64

-> cmd line
```
hive --docker-noshell --client='parity.*master' --sim='.*ethereum.*' --loglevel 10 --results-root /home/sunqi/hive_test/
```
-> log
```
INFO[02-22|11:15:39] docker daemon online                     version=19.03.6
INFO[02-22|11:15:39] building new docker image                pseudoclient=relay nocache=false
Step 1/6 : FROM alpine:latest
 ---> e7d92cdc71fe
Step 2/6 : RUN apk add --update bash
 ---> Using cache
 ---> 72cdf4635cd0
Step 3/6 : RUN apk add socat
 ---> Using cache
 ---> 5889640fd8fa
Step 4/6 : ADD relay.sh /relay.sh
 ---> Using cache
 ---> 37e8a020a18c
Step 5/6 : RUN chmod +x /relay.sh
 ---> Using cache
 ---> 70992683df45
Step 6/6 : ENTRYPOINT ["/relay.sh"]
 ---> Using cache
 ---> 4211ebbff147
[Warning] One or more build-args [branch] were not consumed
Successfully built 4211ebbff147
Successfully tagged hive/pseudoclients/relay:latest
INFO[02-22|11:15:39] Creating output folder if necessary      folder=/home/sunqi/hive_test/
INFO[02-22|11:15:39] creating ethash container
INFO[02-22|11:15:39] building new docker image                nocache=false
Step 1/3 : FROM ethereum/client-go
 ---> 713a70b46bae
Step 2/3 : RUN   echo '#!/bin/sh'                          > /root/ethash.sh &&   echo 'set -e'                            >> /root/ethash.sh &&   echo 'geth makedag 1 /root/.ethash'      >> /root/ethash.sh &&   echo 'if [ "$UID" != "0" ]; then'        >> /root/ethash.sh &&   echo '  adduser -u $UID -D ethash'       >> /root/ethash.sh &&   echo '  chown -R ethash /root/.ethash/*' >> /root/ethash.sh &&   echo 'fi'                                >> /root/ethash.sh &&   chmod +x /root/ethash.sh
 ---> Using cache
 ---> 8b23b17a58b1
Step 3/3 : ENTRYPOINT ["/root/ethash.sh"]
 ---> Using cache
 ---> f3fc672240a8
[Warning] One or more build-args [branch] were not consumed
Successfully built f3fc672240a8
Successfully tagged hive/internal/ethash:latest
DBUG[02-22|11:15:39] created ethash container
INFO[02-22|11:15:39] generating genesis DAG
DBUG[02-22|11:15:39] attaching to container
DBUG[02-22|11:15:39] starting container
ERROR[02-22|11:15:41.515] Failed to generate mapped ethash dataset epoch=0 err="invalid argument"
INFO [02-22|11:15:48.466] Generating DAG in progress               epoch=0 percentage=0 elapsed=6.929s
...
NFO [02-22|11:27:26.274] Generating DAG in progress               epoch=0 percentage=99 elapsed=11m44.737s
INFO [02-22|11:27:26.276] Generated ethash verification cache      epoch=0 elapsed=11m44.738s
DBUG[02-22|11:27:27] deleting ethash container
INFO[02-22|11:27:28] building simulators for testing          pattern=.*ethereum.*
INFO[02-22|11:27:28] building new docker image                simulator=ethereum/consensus nocache=false
Step 1/17 : FROM golang:1.11-alpine as builder
 ---> e116d2efa2ab
Step 2/17 : RUN apk add --no-cache git make gcc musl-dev linux-headers bash
 ---> Using cache
 ---> 98df6f43b0e9
Step 3/17 : RUN GOPATH=/go
 ---> Using cache
 ---> b69571be2dfa
Step 4/17 : ENV GO111MODULE=off
 ---> Using cache
 ---> 843955fc3551
Step 5/17 : RUN go get -u -v github.com/derekparker/delve/cmd/dlv
 ---> Using cache
 ---> c9ba7583c456
Step 6/17 : ENV GO111MODULE=on
 ---> Using cache
 ---> aab748b2bb37
Step 7/17 : ADD /ethereum/consensus/main.go /go/src/github.com/ethereum/hive/simulators/ethereum/consensus/main.go
EROR[02-22|11:27:29] failed to build docker image             simulator=ethereum/consensus error="ADD failed: stat /var/lib/docker/tmp/docker-builder913851915/ethereum/consensus/main.go: no such file or directory"
DBUG[02-22|11:27:29] terminating simulator server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6c pc=0x6ddef7]

goroutine 1 [running]:
net/http.(*Server).Shutdown(0x0, 0xb10c80, 0xc0002a4000, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2636 +0x47
main.terminateAndUpdate()
        /mnt/shared/go/src/github.com/ethereum/hive/simulator.go:622 +0xe3
main.runSimulations(0x7fffb549e092, 0xc, 0xc00019fec8, 0x0, 0x0, 0x0, 0xb05340, 0xc0001ebfe0)
        /mnt/shared/go/src/github.com/ethereum/hive/simulator.go:38 +0x5e4
main.mainInHost(0xc00019fec8, 0x0, 0x0, 0x0, 0x0, 0x2)
        /mnt/shared/go/src/github.com/ethereum/hive/hive.go:143 +0x35d
main.main()
        /mnt/shared/go/src/github.com/ethereum/hive/hive.go:114 +0x655

```

**Comment by holiman** [comment]
Yep, had the same thing. Fixed now, merging soon
