### ISSUE TITLE
Nethermind problems

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#260]
Log from a hive-run below
It appears to init the genesis correctly, but later, in the same second, when it imports the blocks, it forgets that it's already initalized. 
@tkstanczak any ideas ? 

```
Setting homestead block:0
Setting DAO block:2000
Setting dao vot block:1
Setting tangerine block:0
Setting spurious block:0
Setting byzantium block:0
Setting constantinople block:0
Setting petersburg block:0
Genesis:
{"config":null,"nonce":"0x0","timestamp":"0x0","extraData":"0x00","gasLimit":"0xf4240","difficulty":"0x20000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","coinbase":"0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba","alloc":{"095e7baea6a6c7c4c2dfeb977efac326af552d87":{"code":"0x73095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d8731f260005500","balance":"0x0"},"a94f5374fce5edbc8e2a8697c15331677e6ebf0b":{"balance":"0xde0b6b3a7640000"}},"number":"0x0","gasUsed":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}
Before mapper.jq
{
  "config": {
    "homesteadBlock": 0,
    "daoForkBlock": 2000,
    "daoForkSupport": true,
    "eip150Block": 0,
    "eip158Block": 0,
    "eip155Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0
  },
  "nonce": "0x0",
  "timestamp": "0x0",
  "extraData": "0x00",
  "gasLimit": "0xf4240",
  "difficulty": "0x20000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
  "alloc": {
    "095e7baea6a6c7c4c2dfeb977efac326af552d87": {
      "code": "0x73095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d8731f260005500",
      "balance": "0x0"
    },
    "a94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
      "balance": "0xde0b6b3a7640000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
Chainspec:
{ "name": "Foundation", "dataDir": "ethereum", "engine": { "Ethash": { "params": { "minimumDifficulty": "0x020000", "difficultyBoundDivisor": "0x0800", "durationLimit": "0x0d", "blockReward": { "0x0": "0x1BC16D674EC80000" }, "homesteadTransition": 0, "daoHardforkTransition": "0x2000", "daoHardforkBeneficiary": "0xbf4ed7b27f1d666546e30d74d50d173d20bca754", "daoHardforkAccounts": [], "eip100bTransition": "0x0", "difficultyBombDelays": { "0x0": 2000000 } } } }, "params": { "gasLimitBoundDivisor": "0x0400", "registrar": "0xc6d9d2cd449a754c494264e1809c50e34d64562b", "accountStartNonce": "0x00", "maximumExtraDataSize": "0x20", "minGasLimit": "0x1388", "networkID": "0x1", "forkBlock": "0x2000", "forkCanonHash": "0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb", "eip150Transition": "0x0", "eip160Transition": "0x0", "eip161abcTransition": "0x0", "eip161dTransition": "0x0", "eip155Transition": "0x0", "maxCodeSize": 24576, "maxCodeSizeTransition": "0x0", "eip140Transition": "0x0", "eip211Transition": "0x0", "eip214Transition": "0x0", "eip658Transition": "0x0", "eip145Transition": "0x0", "eip1014Transition": "0x0", "eip1052Transition": "0x0", "eip1283Transition": "0x0", "eip1283DisableTransition": "0x0" }, "genesis": { "seal": { "ethereum": { "nonce": "0x0", "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000" } }, "difficulty": "0x20000", "author": "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba", "timestamp": "0x0", "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "extraData": "0x00", "gasLimit": "0xf4240" }, "nodes": [], "accounts": { "0000000000000000000000000000000000000001": { "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } }, "0000000000000000000000000000000000000002": { "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } }, "0000000000000000000000000000000000000003": { "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } }, "0000000000000000000000000000000000000004": { "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } }, "0x095e7baea6a6c7c4c2dfeb977efac326af552d87": { "code": "0x73095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d873173095e7baea6a6c7c4c2dfeb977efac326af552d8731f260005500", "balance": "0x0" }, "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": { "balance": "0xde0b6b3a7640000" }, "0x0000000000000000000000000000000000000005": { "builtin": { "name": "modexp", "activate_at": "0x0", "pricing": { "modexp": { "divisor": 20 } } } }, "0x0000000000000000000000000000000000000006": { "builtin": { "name": "alt_bn128_add", "activate_at": "0x0", "pricing": { "linear": { "base": 500, "word": 0 } } } }, "0x0000000000000000000000000000000000000007": { "builtin": { "name": "alt_bn128_mul", "activate_at": "0x0", "pricing": { "linear": { "base": 40000, "word": 0 } } } }, "0x0000000000000000000000000000000000000008": { "builtin": { "name": "alt_bn128_pairing", "activate_at": "0x0", "pricing": { "alt_bn128_pairing": { "base": 100000, "pair": 80000 } } } } }, "version": "1" }
Running Nethermind...
Loading standard NLog.config file from /nethermind/NLog.config.
Reading config file from /configs/test.cfg
2020-04-14 15:45:49.0098|Grafana / Prometheus metrics are disabled in configuration 
2020-04-14 15:45:49.9922|Using http://checkip.amazonaws.com to get external ip 
2020-04-14 15:45:50.4712|Generating private key for the node (no node key in configuration) - stored in plain + key store for JSON RPC unlocking 
2020-04-14 15:46:04.1035|Store this password for unlocking the node key for JSON RPC - this is not secure - this log message will be in your log files. Use only in DEV contexts. 
2020-04-14 15:46:04.1346|pVmS4Dhj 
2020-04-14 15:46:04.1888|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body  
2020-04-14 15:46:04.2643|HIVE initialization starting 
2020-04-14 15:46:04.2690|HIVE_CHAIN_ID: 1 
2020-04-14 15:46:04.2690|HIVE_BOOTNODE:  
2020-04-14 15:46:04.2690|HIVE_TESTNET:  
2020-04-14 15:46:04.2690|HIVE_NODETYPE:  
2020-04-14 15:46:04.2733|HIVE_FORK_HOMESTEAD: 0 
2020-04-14 15:46:04.2733|HIVE_FORK_DAO_BLOCK: 2000 
2020-04-14 15:46:04.2733|HIVE_FORK_DAO_VOTE: 1 
2020-04-14 15:46:04.2733|HIVE_FORK_TANGERINE: 0 
2020-04-14 15:46:04.2733|HIVE_FORK_SPURIOUS: 0 
2020-04-14 15:46:04.2770|HIVE_FORK_METROPOLIS:  
2020-04-14 15:46:04.2770|HIVE_FORK_BYZANTIUM: 0 
2020-04-14 15:46:04.2770|HIVE_FORK_CONSTANTINOPLE: 0 
2020-04-14 15:46:04.2770|HIVE_FORK_PETERSBURG: 0 
2020-04-14 15:46:04.2770|HIVE_MINER:  
2020-04-14 15:46:04.2817|HIVE_MINER_EXTRA:  
2020-04-14 15:46:04.2853|HIVE Chain file does not exist: /chain.rlp, skipping 
2020-04-14 15:46:04.2919|HIVE Loading blocks from /blocks 
2020-04-14 15:46:04.3450|HIVE Processing block file: /blocks/0001.rlp - 1 (0x37be00...83a89c) 
2020-04-14 15:46:04.4217|Step SetupHive                failed after 151ms System.InvalidOperationException: Block tree should be initialized with genesis before suggesting other blocks.
   at Nethermind.Blockchain.BlockTree.SuggestBlock(Block block, Boolean shouldProcess) in /src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 606
   at Nethermind.Runner.Hive.HiveRunner.ProcessBlock(Block block) in /src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs:line 164
   at Nethermind.Runner.Hive.HiveRunner.InitializeBlocks(String blocksDir) in /src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs:line 147
   at Nethermind.Runner.Hive.HiveRunner.Start() in /src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs:line 62
   at Nethermind.Runner.Ethereum.Steps.SetupHive.Execute() in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupHive.cs:line 44
2020-04-14 15:46:04.4979|FAILED TO INIT SetupHive System.InvalidOperationException: Block tree should be initialized with genesis before suggesting other blocks.
   at Nethermind.Blockchain.BlockTree.SuggestBlock(Block block, Boolean shouldProcess) in /src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 606
   at Nethermind.Runner.Hive.HiveRunner.ProcessBlock(Block block) in /src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs:line 164
   at Nethermind.Runner.Hive.HiveRunner.InitializeBlocks(String blocksDir) in /src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs:line 147
   at Nethermind.Runner.Hive.HiveRunner.Start() in /src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs:line 62
   at Nethermind.Runner.Ethereum.Steps.SetupHive.Execute() in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupHive.cs:line 44
2020-04-14 15:46:04.5927|Found 1 blocks to load from DB starting from current head block  
2020-04-14 15:46:04.6145|Missing level - 0 
2020-04-14 15:46:05.2711|HIVE new head block 0 (0x729b1a...ebba7d) 
2020-04-14 15:46:06.4384|Sync peers - Initialized: 0 | All: 0 | Max: 50 
2020-04-14 15:46:06.4565|Loaded 0 static nodes from file: /nethermind/Data/static-nodes.json 
2020-04-14 15:46:06.4784|Sync peers 0(0)/50, searching for peers to sync with... 
2020-04-14 15:46:06.8441|No bootnodes specified in configuration 
2020-04-14 15:46:06.8756|ReceiptsDb migration disabled. Finding logs when multiple blocks receipts need to be scanned might be slow. 
2020-04-14 15:46:07.2813|
======================== Nethermind initialization completed ========================
Version      : 1.7.18-0-d38eaae5d-20200414/X64-Linux 4.15.0-91-generic/Core3.1.3
This node    : enode://65e6ed86bf9d9655588182e115e8f41c9c0cf2db09c57e617caf5fa4529eacbd737eb1a7b003ebe2be6c1dfc3eb67466ce0af76539a7010bdd04b0903f6ce41f@46.59.37.153:30303
Node address : 0xfa91cb7b8e1d827512561f764f4c685db1cdac9c (do not use as an account)
Mem est tx   :     40MB
Mem est trie :    200MB
Mem est peers:     50MB
Mem est netty:    268MB
Mem est      :    558MB
Genesis hash : 0x729b1a632ff8cf6ed82476b9fef83507b8fb8a1b829cbfecf771965c77ebba7d
External IP  : 46.59.37.153
Ethereum     : tcp://46.59.37.153:30303
Discovery    : udp://172.18.0.12:30303
Chainspec    : /chainspec/test.json
Chain head   : 0
Chain ID     : MainNet
===================================================================================== 
2020-04-14 15:46:07.9850|Error when handling ID 1, eth_getBlockByNumber(0x0,False) | {"jsonrpc":"2.0","error":{"code":-32600,"message":"eth_getblockbynumber found but the containing module is disabled"},"id":1} 
2020-04-14 15:46:08.0139|Error when handling ID 2, eth_getBlockByNumber(0x0,False) | {"jsonrpc":"2.0","error":{"code":-32600,"message":"eth_getblockbynumber found but the containing module is disabled"},"id":2} 
2020-04-14 15:48:06.5104|Sync peers - Initialized: 0 | All: 0 | Max: 50 
2020-04-14 15:48:06.5104|Sync peers 0(0)/50, searching for peers to sync with... 
```

**Comment by holiman** [comment]
Hm. I thought that this meant that genesis was imported:
```
2020-04-14 15:46:04.1888|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body  
```

But maybe it means there's nothing there. So how does one get the genesis into nethermind?

**Comment by holiman** [comment]
This seems to be out of order:
```
2020-04-14 15:46:04.2919|HIVE Loading blocks from /blocks 
2020-04-14 15:46:04.3450|HIVE Processing block file: /blocks/0001.rlp - 1 (0x37be00...83a89c) 
2020-04-14 15:46:04.4217|Step SetupHive                failed after 151ms 
...
2020-04-14 15:46:04.5927|Found 1 blocks to load from DB starting from current head block  
2020-04-14 15:46:04.6145|Missing level - 0 
2020-04-14 15:46:05.2711|HIVE new head block 0 (0x729b1a...ebba7d) 
```
It first tries to import blocks, and _then_ load up the genesis.. ?

**Comment by tkstanczak** [comment]
hi, sorry, I probably do not get notified on mentions on GitHub (or just missed it)
Sebastian will be looking at it now and we will try to resolve together - thanks!

**Comment by holiman** [comment]
Sweet!
Don't know if you've seen, but there's now a `test.sh` script in the hive root. You can disable things not related to nethermind, and e.g only do this: https://github.com/ethereum/hive/blob/master/test.sh#L68  (sync nethermind with nethermind). 

It's a bit much to run the full thing on a laptop, but the testscript is tuned down so it's perfectly doable.
