### ISSUE TITLE
Running hiveview on windows fails to an error

### ISSUE THREAD

**Issue by KillariDev** [ethereum/hive#903]
When I try to run hiveview, i am getting following error on windows. The directory is clearly an absolute path, so not sure what the error is about:
```
C:\projects\hive\cmd\hiveview>hiveview -serve -logdir C:/Users/killa/Downloads/workspace/
X [ERROR] The working directory "/" is not an absolute path

panic: The working directory "/" is not an absolute path

goroutine 1 [running]:
main.newBundler({0x17667e0?, 0xc0000a27e0}, {0xc0000e0280, 0x5, 0x5}, 0xc000116f00)
        C:/projects/hive/cmd/hiveview/esbuild.go:43 +0x205
main.hiveviewBundler(...)
        C:/projects/hive/cmd/hiveview/deploy.go:25
main.newDeployFS({0x17667e0?, 0xc0000a27e0}, 0xc0000cbf00)
        C:/projects/hive/cmd/hiveview/deploy.go:65 +0x105
main.runServer({{0x153cd29, 0xc}, {0xc0000c0060, 0x23}, {0x0, 0x0}, 0x0})
        C:/projects/hive/cmd/hiveview/serve.go:51 +0xd7
main.main()
        C:/projects/hive/cmd/hiveview/main.go:39 +0x3f6
```

**Comment by s1na** [comment]
Posting this in case someone needs a workaround. I have one built at https://hub.docker.com/r/sinamahmoodi/hiveview which I probably won't update:

```Dockerfile
FROM golang:1-alpine as builder

COPY ./ /hive

WORKDIR /hive
RUN go build ./cmd/hiveview
RUN mv ./hiveview /usr/local/bin/hiveview

FROM alpine:latest
COPY --from=builder /usr/local/bin/hiveview /usr/local/bin/hiveview

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/hiveview", "-serve", "-logdir", "/workspace"]
```
